"""Added models actuator name with default value

Revision ID: 3b4650d51fc1
Revises: 8975582390c7
Create Date: 2026-04-03 20:12:38.655846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4650d51fc1'
down_revision: Union[str, Sequence[str], None] = '8975582390c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    op.add_column('actuators', sa.Column('actuator_name', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('actuators', 'actuator_name')
    # ### end Alembic commands ###
