"""Added models positive id constraint

Revision ID: 8975582390c7
Revises: 
Create Date: 2026-02-13 23:31:34.650229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8975582390c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###
    op.create_check_constraint("check_id_prototype_positive", "prototypes", "prototype_id >= 0")
    op.create_check_constraint("check_id_sensor_positive", "sensors", "sensor_id >= 0")
    op.create_check_constraint("check_id_measurement_positive", "measurements", "measurement_id >= 0")
    op.create_check_constraint("check_id_actuator_positive", "actuators", "actuator_id >= 0")


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("check_id_prototype_positive", "prototypes", type_="check")
    op.drop_constraint("check_id_sensor_positive", "sensors", type_="check")
    op.drop_constraint("check_id_measurement_positive", "measurements", type_="check")
    op.drop_constraint("check_id_actuator_positive", "actuators", type_="check")
