"""Added actuator name to database

Revision ID: ff1715da2928
Revises: 8975582390c7
Create Date: 2026-03-27 18:58:43.270291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1715da2928'
down_revision: Union[str, Sequence[str], None] = '8975582390c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    op.add_column('actuators', sa.Column('actuator_name', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint("check_actuator_name_not_empty", "actuators", "actuator_name != ''")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('actuators', 'actuator_name')
    # ### end Alembic commands ###
    op.drop_constraint("check_actuator_name_not_empty", "actuators", type="check")
