POST_MEASURMENTS_TOKEN = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJtaXNzaW9ucyI6MSwiZXhwIjoxNzAwNTk4MDcxfQ.mZbCxkeEgL-qGBI1C1RIXslRf_Vi6lkVUH8zMMxCgu4",
)
GET_MEASURMENTS_TOKEN = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJtaXNzaW9ucyI6MiwiZXhwIjoxNzAwNTk4MDcxfQ.IZq-5i2NXYmWM-m3l6sL1BRBQ3S6pdKo7-TkYh3pSH8",
)
MODIFY_SENSOR_AND_PROTOTYPES_TOKEN = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJtaXNzaW9ucyI6NCwiZXhwIjoxNzAwNTk4MDcxfQ.xHWb6XR31IlapiMbXoRnbBAJuK2mBeN-ZkNeK-enpNM",
)