name: Backend

on:
  workflow_dispatch:
  push:
    paths:
      - "backend/**/*.py"
  pull_request:
    paths:
      - "backend/**/*.py"

jobs:
  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run Black formatter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./backend/app/"
      - name: Run PyLint
        run: pylint -f github backend/app/
